# Docs: https://aka.ms/yaml
name: $(Build.DefinitionName)-$(Date:yyyyMMdd))
trigger:
  - main

pool:
  vmImage: 'windows-2022'

variables:
  - group: AKV

stages:
  - stage: Setup
    jobs: 
      - job: Setup
        steps:
          - powershell: .\bootstrap.ps1
            displayName: 'Install pre-requisites'

  - stage: Release
    dependsOn: 'Test'
    jobs:
      - job: Build
        steps:
          - powershell: Invoke-Build -Configuration 'Production' -Task Clean, CopyModuleFiles
            displayName: 'Build PowerShell Module'
            env:
              PSGalleryAPIKey: $(PSGalleryAPIKey)
      - job: Release
        steps:
          - powershell: Invoke-Build -Configuration 'Production' -Task PublishModule
            displayName: 'Publish PowerShell Module'
            env:
              PSGalleryAPIKey: $(PSGalleryAPIKey)
        